GET http://localhost:3100/todos/?status=TO%20DO
####

GET http://localhost:3100/todos/2
####

POST http://localhost:3100/todos/
Content-Type: application/json

{
  "id": 10,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO"
}
####

PUT  http://localhost:3100/todos/2
Content-Type: application/json

{
  "todo": "Some task"
}
###

DELETE http://localhost:3100/todos/1
